### ISSUE TITLE
Infrastructure configuration of send letter for vault still refers to old send letter consumer

### ISSUE THREAD

**Issue by nitinprabhu** [hmcts/send-letter-service#184]
### What would you like to change?

- In `main.tf ` path to the vault secrets still contains reference to old send letter consumer.

```
data "vault_generic_secret" "ftp_user" {
       path = "secret/${var.vault_section}/cc/send-letter-consumer/ftp-user"
 } 
```

### How do you think that would improve the project?

- We would first need to save vault secrets in different path 
```  "secret/${var.vault_section}/cc/send-letter/ftp-user"```

- Then update the config in `main.tf` to reflect updated path.

**Comment by doncem** [comment]
References are gone, closing
